version: '3.8'
services:
  api:
    build: .
    container_name: btg_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/btg_fondos
      - JWT_SECRET=super_secret_key
      - NODE_ENV=production
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: btg_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
